#!/bin/bash
echo "{
    \"device_name\": \"$HOSTNAME\",
    \"listening_port\": $BT_PORT,
    \"lan_encrypt_data\": true,
    \"storage_path\": \"/btsync/.sync\",
    \"pid_file\": \"/var/run/btsync/btsync.pid\",
    \"check_for_updates\": false,
    \"use_upnp\": false,
    \"download_limit\": 0,
    \"upload_limit\": 0,
    \"send_statistics\": false,
    \"shared_folders\": [
        {
            \"secret\": \"$BT_SECRET\",
            \"dir\": \"/data\",
            \"use_relay_server\": false,
            \"use_tracker\": false,
            \"search_lan\": false,
            \"use_sync_trash\": false,
            \"known_hosts\": [
              $BT_KNOWN_HOSTS
            ]
        }
    ]
}" > /btsync/btsync.conf

btsync --config /btsync/btsync.conf --nodaemon $@
